### ISSUE TITLE
Readme..??

### ISSUE THREAD

**Issue by TheoBr** [Maximus-/Grove#37]
A Github project with no readme? Cmon guys

**Comment by DHowett** [comment]
"Cmon guys" turns this from a nice useful issue report to a self-entitled
rant. :(

**Comment by TheoBr** [comment]
@DHowett I was in the room with them when I posted this.

They are receiving course credit at RPI for their work on this project and we have a specific set expectations for any project receiving credit within RCOS.

**Comment by DHowett** [comment]
Good word, am I ever obtuse. I'm really sorry. I suppose I've provided an
accidental lesson in dealing with hostile mailing list people ;P

**Comment by TheoBr** [comment]
@DHowett I used to contribute to Cyanogenmod, this is anything but out of the ordinary to me

Apology accepted, I had a good laugh

**Comment by TheoBr** [comment]
https://github.com/Maximus-/Grove/commit/5fcacfd0743ad62ac7da3cf8bcd7e3679597d1a8
